<?php
$lang = array(
'My Projects' => 'My Projects',
'termbase' => 'Term Base (TB)',
'tm' => 'Translation Memory (TM)',
'community' => 'Community',

'search_default' => 'Search by project name or creator...',
'search' => 'Search',
'nothing' => 'No results.',
'language_pairs' => 'Language pair:',
'creators' => 'Creator:',
'file_name' => 'Filename',
'completeness' => 'Progress:',
'operation' => 'Operation',
# Operation is a generic word - what is the context?
'preview' => 'Preview',
'upload_file_not_leave' => 'Uploading, please don\'t close this window.'
'go_back' => 'Go back',
'source' => 'Source text',
'save' => 'Save',
'cancel' => 'Cancel',
'edit' => 'Edit',
'one_hundred_percent' => '100%',
'hash' => '#',
'created_date' => 'Creation date',
'corresponding_tb' => ' Corresponding TB',
# It's not clear what corresponding TB is - do you mean a word in the source segment matches a term in the term base?
'name' => 'Name',
'description' => 'Description',
'creator' => 'Creator',
'no_tb_created' => 'No term bases available.',
'corresponding_tm' => 'Corresponding TM',
'no_tm_created' => 'No translation memories available.',
'deletefile_or_not' => 'Do you wish to delete this file?',
'choose_file' => 'Choose file',
'no_upload_file' => 'No uploaded file',
# Need more context on 'no_upload_file'
'upload_file' => 'Upload file',

'add_tb' => 'Add a TB',
'no_tb_added' => 'You haven’t added any term bases. Add one now.',
'add_tm' => 'Add a translation memory',
'no_tm_added' => 'You haven’t added any translation memories. Add one now.',
'forty_five_percent' => '45%',
'type_email' => 'Please enter a correct e-mail address.',
'submitting' => 'Submitting...',
'email_not_signed' => 'This e-mail address hasn’t been verified.',
'find_password' => 'Reset password',
'type_signed_email' => 'Please enter your e-mail address to reset your password:',
'send_email' => 'Send a reset e-mail',
# I assume this means to send an email to help the user reset their password
'remind_email_no_signed' => 'If notice the e-mail address is not registered, please',
# It's not clear what 'remind_email_no_signed' is for. Needs some editing
'create_account' => 'Register',
# 'Register' has the same meaning as 'create an account'
'period' => '.',
# This period might be a part of strings concatenated together. This can cause problems, I recommend not concatenating strings
'type_invitationcode' => 'Please enter an invitation code',
'invitationcode' => 'Invitation Code',
'join' => 'Sign Up',
# What is the difference between 'create_account' and 'join'? 'Sign Up' is a good phrase that also means 'register' or 'join'
'login' => 'Login in',
'email' => 'E-mail',
'password' => 'Password',
'sign_in' => 'Sign in',
# Sign in is typically an action to log in. 'Register' means to create a new account.
'forget_password' => 'Forgot password?',
'personal_homepage' => 'My homepage',
'user_names' => 'Username:',
'emails' => 'E-mail:',
'completed_projects' => 'Completed projects:',
# no need to use the (parentheses) around s. If it's one project or 0 or many, it's understood fine :)
// 'created_projects' => ' Created project(s):',
// 'joined_projects' => ' Joined project(s):',
'binned_project' => 'Archived Projects',
'project_name' => 'Project name',
'project_description' => 'Description',
'language' => 'Language',
'former_participant' => 'Former participants:',
# What are former participants?

'no_binned_project' => 'No archived projects.',
'create_new_project' => 'Create a new project',
'en_zh' => 'En-Zh',
'zh_en' => 'Zh-En',
'create' => 'Create',
'created_project' => 'Projects',
# I think no need to say 'created'? We'll have to see what the context is.
'create_project' => 'Create a project',
'participant' => 'Participants',
# Participants are... translators? Users? We should choose a more specific term
'create_first_project' => 'You haven’t created any projects. Create one now!',
'joined_project' => 'My projects:',
# More context on this? "My Projects" could be a better string
'fifty_percent' => '50%',
'bin_project_or_not' => 'Are you sure you want to archive the selected projects?',
'exit_project_or_not' => 'Close project?',
'complete_project_or_not' => 'Are you sure you want to complete this project?',
'confirm_reset' => 'Are you sure you want to reset your password?',
# What are we resetting? Password, I assume?
'type_again' => 'Please try again.',
'twicepsw_different' => 'The two passwords do not match.',
'resetpsw_successfully' => 'Password successfully reset. Please login in again.',
'please_wait' => 'Please wait.',
'user_no_existed' => 'User does not exist.',
'confirm_signin' => 'Are you sure you want to sign in?',
# Need clarification: sign in / register / sign up / log in. All are different...
'check_information_completed' => 'Please complete all fields.',
'email_format_error' => 'Invalid email address.',
'username_existed' => 'Username already exists.',
'email_existed' => 'Email already exists',
'signin_successfully' => 'Registration complete. Please sign in.',
'submit_failed' => 'Failed to submit.',
'user_name' => 'Username',
'link_expired' => 'The link has expired.',
'reset_password' => 'Reset the password on the form.',
# Not sure what the context is of 'reset_password'
'invalid_link' => 'Invalid link',

'wrong_link' => 'Incorrect link',
'password_reset' => ' Reset password',
'new_password' => 'New password',
'confirm_password' => 'Confirm password',
'email_sent' => 'Please click the link in the email sent to the given email address to reset your password.',
'create_new_tb' => 'Create a new term base',
'tb_name' => 'TB Name',
'tb_description' => 'Description',
'add_termpair' => 'Add a term',
'choose_excel' => 'Choose an Excel workbook',
'not_upload_excel' => 'No uploaded Excel workbook',
# It's not clear what this 'not_upload_excel' string is for
'import_excel' => 'Import Excel workbook',
'en' => 'English',
'zh' => 'Chinese',
'add' => 'Add',
'export_excel' => 'Export as Excel workbook',
'termpair_id' => 'Term ID',
'add_first_termpair' => 'You haven’t added any terms. Add one now.',
'two' => '2',
'translation_pair' => 'Translation ID',
'tm_search_default' => 'Search a translation memory',
'descriptions' => 'Description:',
'dates' => 'Date:',
'view' => 'View',

'created_tm' => ' Created TM',
# The context of this 'created_tm' string is not clear. It could be a confirmation message or a header of created TMs.
'create_tm' => 'Create a TM',
'tm_name' => 'TM name',
'tm_description' => 'Description',
'belonged_project' => 'Subordinate project',
# Need more context on 'belonged_project'
'deletetm_or_not' => 'Are you sure you want to delete this TM?',
'tm_machinetrans' => 'TM & Machine Translation',
'term' => 'Term',
'history' => 'Revision History',
'click_source' => '(Click the source text to get Buff)',
# "buff" is not clear, what is the context?
'target' => 'Translation',
// 'eighty_percent' => '80%',
'welcome' => 'Welcome to ',
's_personal_homepage' => ' Homepage',
'delete_failed' => 'Failed to delete.',
'delete_successfully' => 'Successfully deleted.',
'recover_failed' => 'Failed to restore. Please try again.',
'recover_successfully' => 'Successfully restored.',
'save_failed' => 'Failed to save.',
'invite_failed' => 'Failed to join. Please try again.',

'invite_successfully' => 'Successfully joined!',
'invitationcode_error' => 'Incorrect Invitation Code!',
'quit_joinfailed' => 'You have left this project and cannot join again.',
'joined_already' => 'Yoy have already joined this project.',
'quit_failed' => 'Failed to quit',
'quit_successfully' => 'Successfully quit.',
'emailorpassword_affirm' => 'Incorrect e-mail address or password. Please confirm and try again.',
'projectname_blank' => 'Project name cannot be empty.',
'dataadd_failed' => 'Data error:',
'bin_failed' => 'Failed to archive.',
'bin_successfully' => 'Successfully archived. You can restore this project under "My Account" in the top right.',
'tmoutput_failed' => 'Failed to export TM. Please try again.',
'failed_tryagain' => 'Data error. Please try again.',
'project_finished' => 'Project complete.',
'addfailed_tryagain' => 'Failed to add. Please try again.',
'add_successfully' => 'Successfully added.',
'addtb_already' => 'You have already added this TB.',
'move_failed' => 'Failed to move.',
'move_successfully' => 'Successfully moved.',
'addtm_already' => 'You have already added this TM.',
'success' => 'Success',
'tbname_blank' => 'TB name cannot be empty.',

'file_existed' => 'File already exists.',
'upload_failed' => 'Failed to upload.',
'upload_successfully' => 'Successfully uploaded.',
'langpair_uncomplete' => 'Please enter a complete language pair.',
'dataadd_failed' => 'Data error:',
'tmname_blank' => 'TM name cannot be empty.',
'user' => 'User',
'time' => 'Date',
'machine_translation' => 'Machine Translation',
'origin' => 'Source',
'Baidu' => 'Baidu',
'English' => 'English',
'chinese' => 'Chinese',
'account' => 'My Account',
'quit' => 'Quit',

// 'minicat_findpsw' => 'MINICAT - Retrieve password',
// 'dear_user' => 'Dear user',
// 'you_in' => 'You\'ve submitted a request of retrieving your password at',
// 'click_link' => 'Please click the link(valid for 24 hours) below to reset your password.',
// 'visit_link' => 'If the link is not accessible, please copy it to a browser address bar to visit.',
// 'negelect_email' => 'If you didn\'t submit any request of retrieving password, please ignore this e-mail.',
'illegal_str' => 'Illegal string',
'tb_search_default' => 'Search a TB',
'created_tb' => 'Created TB',
'create_tb' => 'Create a TB',
'deletetb_or_not' => 'Do you really want to delete this TB?',
'create_new_tm' => 'Create a new TM',
'add_tmpair' => 'Add TM pair',
'add_first_tmpair' => 'You haven\'t added any language pairs. Add one now.',

'import_tmx'=>'Import TMX file',
'deleteproject_or_not'=>'Do you really want to delete this project? This operation cannot be reversed.',
'ten_percent'=>'10%',
'similarity' => 'Similarity'
);